### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by moeric** [hgenru/wercker-gulp-step#2]
Hi, I've been trying to figure out how to make this step to work but I've had no success so far, this is my wercker.yml contents:

box: debian
build:
  steps:
    - hgen/gulp:
        cwd: master/
        tasks: build

And this the response from wercker:

export WERCKER_STEP_ROOT="/pipeline/gulp-34f8cc6f-3f93-480d-95b8-91e08ae5fc9d"
export WERCKER_STEP_ID="gulp-34f8cc6f-3f93-480d-95b8-91e08ae5fc9d"
export WERCKER_STEP_OWNER="hgen"
export WERCKER_STEP_NAME="gulp"
export WERCKER_REPORT_NUMBERS_FILE="/report/gulp-34f8cc6f-3f93-480d-95b8-91e08ae5fc9d/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/gulp-34f8cc6f-3f93-480d-95b8-91e08ae5fc9d/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/gulp-34f8cc6f-3f93-480d-95b8-91e08ae5fc9d/artifacts"
export WERCKER_GULP_TASKS="build"
source "/pipeline/gulp-34f8cc6f-3f93-480d-95b8-91e08ae5fc9d/run.sh" < /dev/null
gulp is available locally
/pipeline/gulp-34f8cc6f-3f93-480d-95b8-91e08ae5fc9d/run.sh: line 35: node: command not found
gulp version: 
node ./node_modules/gulp/bin/gulp.js build
/pipeline/gulp-34f8cc6f-3f93-480d-95b8-91e08ae5fc9d/run.sh: line 70: node: command not found
127
failed: gulp command failed

Any help would be greatly appreciated, thanks.

**Comment by hgenru** [comment]
@moeric try create custom debian box with installed nodejs package.
